// Dump the local portfolio database to SQL for loading into D1:
//
//   sqlite3 data/portfolio.sqlite "PRAGMA wal_checkpoint(TRUNCATE);"
//   node scripts/export-to-d1.mjs > /tmp/seed.sql
//   wrangler d1 execute psx-portfolio --remote --file=/tmp/seed.sql
//
// The checkpoint is hygiene rather than a rescue: this script reads through
// better-sqlite3, which sees WAL contents regardless. Note that a large -wal
// sidecar does not imply unflushed data — SQLite grows the WAL to a high-water
// mark and reuses it instead of truncating. Checkpointing first just removes
// the ambiguity for anything that copies the raw file.

import Database from "better-sqlite3";
import { existsSync } from "fs";
import { dirname, resolve } from "path";
import { fileURLToPath } from "url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DB_PATH = process.env.PORTFOLIO_DB ?? resolve(ROOT, "data/portfolio.sqlite");

if (!existsSync(DB_PATH)) {
  console.error(`[psx] ${DB_PATH} not found`);
  process.exit(1);
}

// Order matters: holdings before payouts (FK), and every table cleared first so
// the seed is idempotent and can be re-run after a schema reset.
const TABLES = [
  "holdings",
  "payouts",
  "cash",
  "targets",
  "investments",
  "transactions",
  "fee_config",
  "portfolio_history",
  "meta",
];

const lit = (v) => {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "NULL";
  if (Buffer.isBuffer(v)) return `X'${v.toString("hex")}'`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const db = new Database(DB_PATH, { readonly: true });

const out = [];
out.push("-- Generated by scripts/export-to-d1.mjs");
out.push(`-- Source: ${DB_PATH}`);

// Clear in reverse dependency order.
for (const t of [...TABLES].reverse()) out.push(`DELETE FROM ${t};`);

let total = 0;
for (const table of TABLES) {
  const rows = db.prepare(`SELECT * FROM ${table}`).all();
  if (rows.length === 0) continue;
  const cols = Object.keys(rows[0]);
  out.push(`-- ${table}: ${rows.length} row(s)`);
  for (const row of rows) {
    const values = cols.map((c) => lit(row[c])).join(", ");
    out.push(`INSERT INTO ${table} (${cols.join(", ")}) VALUES (${values});`);
  }
  total += rows.length;
}

db.close();

if (total === 0) {
  console.error("[psx] refusing to emit an empty seed — is the database populated?");
  process.exit(1);
}

console.error(`[psx] emitted ${total} row(s) across ${TABLES.length} table(s)`);
process.stdout.write(out.join("\n") + "\n");
